#!/usr/bin/env perl
use strict;
use warnings;

BEGIN { push @INC, $0 =~ s/[^\/]+$/../r }

$|++;

use phiboot;
use phibootmacros;
use phiparse;
use phiobj;
use philang;
use phiops;
use phifront;

use List::Util;
use Time::HiRes qw/time/;

# Test code
sub test
{
  my $method = $_[0] eq 'trace' ? shift : 'run';
  my $ilist = l l(i_crash), i_rset, @_;
  my $st = time;
  my $i  = phiboot::i->new->push($ilist)->i2->$method;
  my $dt = 1000 * (time - $st);
  printf "%.2fms: %s\n", $dt, $$i[0];
}

print "\n> ";
while (<STDIN>)
{
  eval
  {
    test l(pstr $_, pint 0, phifront::root_scope),
         lit phiops::opener, philang::expr, i_eval, i_eval,
         tail, head, swap, mcall"abstract", mcall"val";
  };
  print "ERROR: $@" if $@;
  print "\n> ";
}
