#!/usr/bin/env perl
use strict;
use warnings;

use Carp;

$SIG{__DIE__} = sub {Carp::confess(@_)};

do 'parser.pm';
do 'parsestr.pm';
do 'editor.pm';

package phi;
use JSON;

use constant je => JSON->new->allow_blessed(1)->allow_nonref(1);

my $str    = 'foobar';
my $doc    = phi::parser::strinput->new($str);
my $parser = phi::parser::seq_fixed->new(
  phi::parser::strconst->new('foo'),
  phi::parser::alt_fixed->new(
    phi::parser::strconst->new('bar'),
    phi::parser::strconst->new('0')));

my $generator = phi::parser::map->new($parser, sub {
  join "", map $_->val, @{$_[0]}
});

my $result = $generator->on($doc, 0);

print "initial parse output: " . je->encode($result->val) . "\n";
$str = 'foo0bif';
print "updated parse result: " . je->encode($result->parse(3)->val) . "\n";
