#!/usr/bin/env perl
use strict;
use warnings;

BEGIN { push @INC, $0 =~ s/[^\/]+$/../r }

$|++;

use phiboot;
use phibootmacros;
use phiparse;
use philocal;
use phiobj;
use phiabstract;

use List::Util;
use Time::HiRes qw/time/;

# Test code
sub test
{
  my $method = $_[0] eq 'trace' ? shift : 'run';
  my $ilist = l @_;
  my $st = time;
  my $i  = phiboot::i->new->push($ilist)->i2->$method;
  my $dt = 1000 * (time - $st);
  printf "%.2fms: %s\n", $dt, $$i[0];
}

print "abstract interpreter\n";
test pcons(l('ds', 'cs', 'rs'), abstract_interpreter), mcall"d";
test pcons(l('ds', 'cs', 'rs'), abstract_interpreter), mcall"c";
test lit 'X', pcons(l('ds', 'cs', 'rs'), abstract_interpreter),
              mcall"dset", head;
test lit 'X', pcons(l('ds', 'cs', 'rs'), abstract_interpreter),
              mcall"cset", head;

test al(psym 'X'), abstract_interpreter_new, mcall"dset", mcall"dpop", swap, drop;
test lit 'X', abstract_interpreter_new, mcall"dpush", mcall"d", ahead;
test lit 'X', abstract_interpreter_new, mcall"dpush", mcall"dpop", swap, drop;
test lit 'X', pcons(l(al('ds'), al('cs')), phiabstract::abstract_interpreter),
              mcall"cpush", mcall"dpop", swap, drop, mcall"val";

test abstract_interpreter_new,
     mcall"gensym", swap, mcall"gensym", swap, mcall"gensym", swap, drop;

print "abstract interpreter cpack\n";
test abstract_interpreter_new,
     al('c'), swap, mcall"cpush",
     apnil,   swap, mcall"cpush",
     apnil,   swap, mcall"cpush",
     mcall"cpack", mcall"has-next?";

print "abstract interpreter next-insn\n";
test abstract_interpreter_new,
     al('d'),           swap, mcall"cpush",
     al('a', 'b', 'c'), swap, mcall"cpush",
     apnil,             swap, mcall"cpush",
     mcall"cpack", mcall"next-insn", mcall"val", swap, drop;

test pcons(l('ds', al(apnil, al('a', 'b', 'c'), al('d')), pnil, 0, pnil),
           phiabstract::abstract_interpreter),
     mcall"cpack",
     mcall"next-insn", drop, mcall"next-insn", drop, mcall"next-insn",
     head, swap, drop;

test pcons(l('ds', al(apnil, al('a', 'b', 'c'), al('d')), pnil, 0, pnil),
           phiabstract::abstract_interpreter),
     mcall"cpack",
     mcall"next-insn", drop, mcall"next-insn", drop, mcall"next-insn",
     drop, mcall"next-insn",
     head, swap, drop;

test pcons(l('ds', al(apnil, apcons(apsym 'a', apsym 'b')), pnil, 0, pnil),
           phiabstract::abstract_interpreter),
     mcall"cpack",
     mcall"next-insn", drop, mcall"next-insn", head, swap, drop;

test abstract_interpreter_new,
     al(2), swap, mcall"cpush",
     mcall"next-insn", isget(0), swap, drop;

print "abstract interpreter eval\n";
test abstract_interpreter_new,
     al(5), swap, mcall"dpush",
     apint(2), mcall"eval",
     mcall"next-insn", isget(0), swap, drop;

print "abstract interpreter step\n";
test abstract_interpreter_new,
     al(1, 2, 3), swap, mcall"dpush",
     al(i_type),  swap, mcall"cpush",
     mcall"step", mcall"dpop", mcall"val", swap, drop;

print "abstract interpreter run\n";
test abstract_interpreter_new,
     apnil,      swap, mcall"dpush",
     al(i_type), swap, mcall"cpush",
     mcall"run", mcall"dpop", mcall"val", swap, drop;

test abstract_interpreter_new,
     apnil,      swap, mcall"dpush",
     apint(4),   swap, mcall"dpush",
     al(i_cons), swap, mcall"cpush",
     mcall"run", mcall"dpop", mcall"head", mcall"val", swap, drop;

test abstract_interpreter_new,
     apnil,                        swap, mcall"dpush",
     apint(4),                     swap, mcall"dpush",
     al(i_cons, i_uncons, i_cons), swap, mcall"cpush",
     mcall"run", mcall"dpop", mcall"head", mcall"val", swap, drop;
