#!/usr/bin/env perl
use strict;
use warnings;

use phiboot;
use phibootmacros;
use phiparse;
use philocal;

use List::Util;
use Time::HiRes qw/time/;

# Test code
sub test
{
  my $method = $_[0] eq 'trace' ? shift : 'run';
  my $ilist = l @_;
  my $st = time;
  my $i  = phiboot::i->new->push($ilist)->i2->$method;
  my $dt = 1000 * (time - $st);
  printf "%.2fms: %s\n", $dt, $$i[0];
}

print "quote tests\n";
test lit "foo", quote, i_eval, i_eval;
test lit 10, quote, i_eval, i_eval;
test l(qw/x y z/), quote, i_eval, i_eval;
