#!/usr/bin/env perl
use strict;
use warnings;

BEGIN { push @INC, $0 =~ s/[^\/]+$/../r }

$|++;

use phiboot;
use phibootmacros;
use phiparse;
use phiobj;
use philang;
use phiops;

use List::Util;
use Time::HiRes qw/time/;

# Test code
sub test
{
  my $method = $_[0] eq 'trace' ? shift : 'run';
  my $ilist = l l(i_crash), i_rset, @_;
  my $st = time;
  my $i  = phiboot::i->new->push($ilist)->i2->$method;
  my $dt = 1000 * (time - $st);
  printf "%.2fms: %s\n", $dt, $$i[0];
}

use phi int_123 => pcons(l(123), phiops::int_type);
use phi int_456 => pcons(l(456), phiops::int_type);

use phi foo_scope =>
  pcons l(pnil,
          l(l(l(pstr "foo", phiparse::str, i_eval),
              l(drop, int_123),
              phiparse::pmap, i_eval),
            phiops::int_literal),
          pnil),
        philang::scope_chain_type;

use phi bar_scope =>      # a child of foo_scope
  pcons l(foo_scope,
          l(l(l(pstr "bar", phiparse::str, i_eval),
              l(drop, int_456),
              phiparse::pmap, i_eval)),
          pnil),
        philang::scope_chain_type;

print "expressions\n";
test l(pstr "foo",        pint 0, foo_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "1357",       pint 0, foo_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "1357+45",    pint 0, foo_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "1357+45+45", pint 0, foo_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";

print "same, but child scope\n";
test l(pstr "foo",        pint 0, bar_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "1357",       pint 0, bar_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "1357+45",    pint 0, bar_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "1357+45+45", pint 0, bar_scope), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";

print "parens\n";
use phi ints_and_parens =>
  pcons l(bar_scope,
          l(phiops::paren_literal,
            phiops::whitespace_literal,
            phiops::line_comment_literal,
            phiops::timesop_literal,
            phiops::int_literal),
          pnil,
          pnil),
        philang::scope_chain_type;

#test l(pstr "4+51", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
#test l(pstr "(4)+51", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
#test l(pstr "4+(51)", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
#test l(pstr "(4)+(51)", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
#test l(pstr "((4))+(51)", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
#test l(pstr "((4)+(51))", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
#test l(pstr "((4)+(48))+3", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "((4)+(47))+((((3+1))))", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";

if (0)
{
print "whitespace\n";
#test l(pstr " 4+51", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
#test l(pstr " 4+ 51", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "   4+  51", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(i_crash), i_rset,
     l(pstr "4 ", pint 0, ints_and_parens), lit phiops::opener, philang::expr,
     i_eval, i_eval, swap, drop, tail, head;

test l(pstr "4  ", pint 0, ints_and_parens), lit phiops::opener, philang::expr,
     i_eval, i_eval, tail, head, swap, mcall"val";

test l(pstr "  4  ", pint 0, ints_and_parens), lit phiops::opener, philang::expr,
     i_eval, i_eval, tail, head, swap, mcall"val";
test l(pstr " 4 +  51", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
}

print "postfix modifiers\n";
test l(pstr "11*5", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "(11*5)*5", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "11 * 5", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "11 * 5 + 1", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "11 + 1 * 5", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr "(11 + 1) * 5", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
test l(pstr " ( 2 + 3  )  *  (  4 + 5 ) ", pint 0, ints_and_parens), lit phiops::opener, philang::expr, i_eval, i_eval, drop, mcall"val";
