sudo: required
services:
- docker

notifications:
  webhooks: https://dev.spencertipping.com/hooks/hnaHP6PadkDWuSfdN/xkoiGNgPyux5YrhFMp4PtjdNsXkM6c9t4eYvM2TdtLjdoYjN

before_intsall:
- docker pull spencertipping/phi-test

script:
- docker run --rm -it -v $PWD:/data spencertipping/phi-test /data/test/travis
