#!/bin/bash
cat phi - <<'EOF' | perl
use JSON;
my $parser = phi::parser::seq->new(
               phi::parser::alt->new(
                 phi::parser::str->new("g"),
                 phi::parser::str->new("f")),
               phi::parser::str->new("oo"));
print encode_json($parser->parse(phi::parser::state::str->new(\"foo", 0))->value), "\n";
EOF
