#!/bin/bash
perl -e '
BEGIN {require "phi.boot"}
while (<STDIN>)
{
  my $parsed = phi::expr->parse(phi::parser::state::str->new(\$_, 0));
  print $parsed->error || phi::je->encode($parsed->value), "\n";
}
'
