#!/bin/bash
last_diff=
while : ; do
  sleep 0.5
  next_diff=`git diff | md5sum`
  if [[ $last_diff != $next_diff ]]; then
    clear
    ocaml str.cma unix.cma phi.ml < test.phi
    last_diff=$next_diff
  fi
done
