#!/bin/bash
# Runs lazytest inside the phi-dev docker image

cd "$(dirname "$0")"

dockerize=yes
docker_image=phi-test
test_cmd="./lazytest boot.md | bash"

while (( $# )); do
  case $1 in
  --no-dockerize)
    dockerize=
    ;;

  --build|--docker-build)
    docker build -t phi-test - < docker/phi-dev/Dockerfile
    ;;

  --repeat)
    original_diff=
    while : ; do
      new_diff=$(git diff | sha256sum)
      if [[ "$new_diff" != "$original_diff" ]]; then
        original_diff="$new_diff"
        clear
        ./test
      fi
      sleep 1
    done
    ;;

  *)
    echo "Unknown option $1" >&2
    exit 1
    ;;
  esac
  shift
done

if [[ -n "$dockerize" ]]; then
  docker run --rm -v "$PWD:/phi" -m 512m phi-test \
    sudo -u \#$UID sh -c "$test_cmd"
else
  sh -c "$test_cmd"
fi
