#!/bin/bash
# Runs tests on every file save.

last_state=
while : ; do
  new_state=`git diff | md5sum`
  if [[ "$new_state" != "$last_state" ]]; then
    clear
    ./test-rewrites
    last_state=$new_state
  fi
  sleep 0.25
done
