#!/bin/bash
set -euo pipefail
shopt -s extglob
cd "$(dirname "$0")/.."

the_diff=$(mktemp -u)
git diff $1 > "$the_diff"

ilines=( "$the_diff" rp'!/^\+\+\+/' rps/^\\+// FSF^S gu )
dlines=( "$the_diff" rp'!/^---/'    rps/^-//   FSF^S gu )

echo "commits:          $(git log --oneline | wc -l)"
echo "commits since:    $(git log --oneline ...$1 | wc -l)"
echo "insertions:       $(ni "${ilines[@]}" rIA[ "${dlines[@]}" ] e'wc -l')"
echo "deletions:        $(ni "${dlines[@]}" rIA[ "${ilines[@]}" ] e'wc -l')"
echo "abs insertions:   $(grep ^+[^+] $the_diff | wc -l)"
echo "abs deletions:    $(grep ^-[^-] $the_diff | wc -l)"

echo "boot code size:   $(ni phi0.pl phi0/*.pm e'wc -l') line(s)"
echo

./build
echo "phi1 size:        $(ni 1p'-s "phi1"')"
echo "phi2 size:        $(ni 1p'-s "phi2"')"
echo "anon allocations: $(ni debug/phi1prod.symbols rp'd =~ /anon/' e'wc -l')"
echo "largest allocations:"
ni debug/phi1prod.symbols OB r10 p'"  $_"' | cat

echo
echo "TODO items:"
grep -c -R TODO phi0* | egrep -v ':0$|\.swp' | sed 's/^/  /' || :
echo

rm "$the_diff"
