#!/bin/bash
shopt -s extglob
cd "$(dirname "$0")/.."

the_diff=$(mktemp -u)
git diff $1 !(shelved) > "$the_diff"

ins="$the_diff rps/^\\+// FSF^S gu"
del="$the_diff rps/^-//   FSF^S gu"

echo "insertions: $(ni $ins rIA[$del] e'wc -l')"
echo "deletions:  $(ni $del rIA[$ins] e'wc -l')"
echo "phi size:   $(ni 1p'-s "phi"')"

rm "$the_diff"
