=head1 License
    phi programming language
    Copyright (C) 2018  Spencer Tipping

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
=cut

package phi;

use strict;
use warnings;


=head2 Bootup strategy
How we get to the endpoint isn't the same as which endpoint we're going for; as
a result, the objects we use to boot phi aren't directly related to the set of
objects we ultimately want.

More specifically, phi ends up being a series of class and bytecode objects that
are here-linked to each other. We have three ways to get the bytecode:

1. Hand-write using C<bin>
2. Use Perl abstraction to compile it
3. Generate method calls to phi objects to ask them to generate it

Of those options, the latter gives us the most reusable leverage. So we need to
hand-write enough stuff to get phi objects that can compile other phi objects.
...and that, of course, means that we need to specify what phi is compiling.

Before we get there, though, we need to build up a world that's expressive
enough to make this not entirely miserable.


=head3 Interpreter protocol
This is a good place to start because it gives us heap allocation, which is
required for basically everything else. It also gives us some useful diagnostic
methods like C<print_string> and C<pnl> ("print with newline"). C<assert> is
used by unit tests and has signature C<< (cond message) -> ()|die >>.

The interpreter provides a mutable string-map of globals that we can use to name
stuff we generate at bootup. This is convenient because not all values exist
within phi0; sometimes we'll want to use phi1's constructor machinery to get to
an endpoint rather than trying prop stuff up in phi0.
=cut

use constant interpreter_protocol => phi::protocol->new('interpreter',
  qw/ heap_allocate
      map_heap
      heap_usage
      globals
      globals=
      def
      global
      print_char
      print_string
      print_string_fd
      pnl
      pnl_err
      die
      assert
      exit /);


=head3 General object-management stuff
The boring details like C<to_string> and C<clone> that are normally factored
into base classes. This is all minimal because we're hand-coding these methods
where they exist (normally a lot of this would be generated by metaclasses).
=cut

use constant clone_protocol => phi::protocol->new('clone',
  qw/ clone /);


=head3 Data structures
I want to keep this fairly minimal for now. We need enough stuff to encode the
structure of classes and bytecode objects, which I think can be built from lists
and maps.


=head4 Linked lists
The usual cons/nil arrangement. C<maybe_nil> is used by more than just cons
cells, so it gets its own protocol.

C<+> is expected to return a new list (or object in general) of the same type as
the receiver.
=cut

use constant maybe_nil_protocol => phi::protocol->new('maybe_nil',
  qw/ nil? /);

use constant cons_protocol => phi::protocol->new('cons',
  qw/ head
      tail /);

use constant cons_relinkable_protocol => phi::protocol->new('cons_relinkable',
  qw/ with_tail /);

use constant joinable_protocol => phi::protocol->new('joinable',
  qw/ + /);

use constant invertible_protocol => phi::protocol->new('invertible',
  qw/ ~ /);

use constant list_protocol => phi::protocol->new('list',
  qw/ length
      reduce
      [] /);

use constant set_protocol => phi::protocol->new('set',
  qw/ contains? /);

use constant mutable_list_protocol => phi::protocol->new('mutable_list',
  qw/ []=
      shift
      << /);

use constant mutable_set_protocol => phi::protocol->new('mutable_set',
  qw/ << /);

use constant linked_list_protocol => phi::protocol->new('linked_list',
  qw/ element==_fn
      root_cons /);


=head4 Key/value maps
For now we can use a linked map structure, basically a cons setup where each
link contains both a key and a value.
=cut

use constant kv_protocol => phi::protocol->new('kv',
  qw/ key
      value /);

use constant mutable_value_protocol => phi::protocol->new('mutable_value',
  qw/ value= /);

use constant map_protocol => phi::protocol->new('map',
  qw/ key==_fn
      keys
      kv_pairs
      {} /);

use constant mutable_map_protocol => phi::protocol->new('mutable_map',
  qw/ {}= /);

use constant linked_map_protocol => phi::protocol->new('linked_map',
  qw/ kvcell_for /);


=head3 Strings and bytecode
C<byte_string> is a low-level byte array, whereas C<string_buffer> is a
self-managing thing that lets you append efficiently using doubling allocation.
=cut

use constant eq_protocol => phi::protocol->new('eq',
  qw/ == /);

use constant byte_string_protocol => phi::protocol->new('byte_string',
  qw/ data
      size /);

use constant string_buffer_protocol => phi::protocol->new('string_buffer',
  qw/ append_string
      append_int
      append_int64
      append_int32
      append_int16
      append_int8
      append_dec
      headroom
      capacity
      reallocate
      rewind
      to_string /);


=head3 Macro assembler
phi code needs to be able to write phi code, because that's how I roll. This
means we'll end up reimplementing parts of C<bin> and various macros into a phi
object that can emit compiled code objects. At the core of this is the macro
assembler, which manages the intermediate buffers and provides a decently
friendly interface for writing functions and stuff.

We need to keep track of any external references we write into code. This is
done by maintaining a list of refs, each of which knows the offset of the
constant (relative to the beginning of the code buffer) and the vtable
corresponding to the ref that was pushed. The vtable matters for GC purposes: we
don't know whether the ref is a base pointer, here pointer, or something else.
=cut

use constant ref_protocol => phi::protocol->new('ref',
  qw/ offset
      pointer_type
      get
      set /);

use constant here_protocol => phi::protocol->new('here',
  qw/ here /);

use constant bytecode_protocol => phi::protocol->new('bytecode',
  qw/ call_native /);

use constant fn_protocol => phi::protocol->new('fn',
  qw/ call
      goto /);

use constant macro_assembler_protocol => phi::protocol->new('macro_assembler',
  qw/ parent
      child
      refs
      code /,

  # Assembler macros (plus some shorthands for numbers)
  # NB: pnl is a macro to simplify debugging. It inserts a literal string
  # followed by a call to i.pnl to print stuff.
  qw/ 0
      1
      2
      3
      4
      l8
      l16
      l32
      l64
      ref<<
      ptr
      hereptr
      dup
      pnl
      debug_trace
      [
      ]
      add_child_link
      inline
      compile /);

use constant insn_proxy_protocol => phi::protocol->new('insn_proxy',
  sort keys %{+insns});


=head2 Metaclass protocols
Classes for these are defined in L<phi0/metaclasses.pm>.
=cut

use constant struct_link_protocol => phi::protocol->new('struct_link',
  qw/ size
      left_offset
      right_offset
      size_fn
      left_offset_fn
      right_offset_fn /);

use constant cons_struct_link_protocol => phi::protocol->new('cons_struct_link',
  qw/ name
      class
      getter_fn
      setter_fn
      get
      set
      fget_fn
      fset_fn
      generate_getter_fn
      generate_setter_fn /);


=head3 Classes and protocols
These are just enough to access the fields within the objects. C<phi1> then
generates new classes that provide compilation logic.
=cut

use constant ctti_protocol => phi::protocol->new('ctti',
  qw/ exists_at_runtime?
      symbolic_method
      resolve
      parse /);

use constant fn_ctti_protocol => phi::protocol->new('fn_ctti',
  qw/ arg_cttis
      return_ctti /);

use constant protocol_protocol => phi::protocol->new('protocol',
  qw/ virtuals
      classes
      struct_link /);

use constant mutable_protocol_protocol => phi::protocol->new('mutable_protocol',
  qw/ defvirtual
      implementors<< /);

use constant class_protocol => phi::protocol->new('class',
  qw/ protocols
      methods
      virtuals
      fields
      struct_link /);

use constant compilable_class_protocol => phi::protocol->new('compilable_class',
  qw/ dispatch_fn /);

use constant mutable_class_protocol => phi::protocol->new('mutable_class',
  qw/ defmethod
      defvirtual
      implement /);


use constant class_test_incdec_protocol =>
  phi::protocol->new('class_test_incdec',
    qw/ inc
        dec /);


=head2 Backdoor reflective protocol
Objects need to implement this protocol so we can invoke their methods
symbolically; i.e. without knowing the vtable index of those methods.
=cut

use constant method_translator_protocol =>
  phi::protocol->new('method_translator',
    qw/ {} /);


use constant symbolic_method_protocol => phi::protocol->new('symbolic_method',
  qw/ symbolic_method /);


1;
