#!/bin/bash
# Runs a shell inside a development docker image that comes preloaded with nasm
# and ni. The repo directory is linked as /phi, and you'll be running as your
# own user ID inside the container. Memory is also limited to prevent runaway
# allocations from taking down your host system.

cd "$(dirname "$0")"

myuser=`grep $USER: /etc/passwd | head -n1`

echo 'Building image...'
docker build - < docker/phi-dev/Dockerfile >/dev/null

docker run --rm -v "$PWD:/phi" -m 512m --hostname phi-dev -it \
  `docker build -q - < docker/phi-dev/Dockerfile` \
  sh -c 'echo "'"$myuser"'" >> /etc/passwd;
         chown '$USER' /root;
         sudo -u \#'$UID' /bin/bash'
